### ISSUE TITLE
Can't install with symfony 4.1

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/panthere#34]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - dunglas/panthere dev-master requires symfony/browser-kit ^4.0 -> satisfiable by symfony/browser-kit[v4.1.0].
    - dunglas/panthere dev-master conflicts with symfony/browser-kit[v4.1.0].
    - dunglas/panthere dev-master conflicts with symfony/browser-kit[v4.1.0].
    - dunglas/panthere dev-master conflicts with symfony/browser-kit[v4.1.0].
    - Installation request for dunglas/panthere dev-master -> satisfiable by dunglas/panthere[dev-master].

Why exactly was the conflict with browser-kit 4.1 added?

**Comment by dunglas** [comment]
This is known issue. Symfony 4.1.0 contains a BC break that impact Panthère. I've fixed it in 4.1, we have to wait for the release of 4.1.1. See symfony/symfony#27485.

**Comment by ChangePlaces** [comment]
Ah, thanks, fingers crossed it's soon. I saw there was a MR to add a 4.1 conflict, but there weren't any issues regarding the matter so I was confused!
