### ISSUE TITLE
Make Panthère use more options for the Chrome driver

### ISSUE THREAD

**Issue by Pierstoval** [symfony/panthere#50]
I came across [this Docker config](https://github.com/westy92/headless-chrome-alpine/blob/master/Dockerfile) to run Chromium headless on Alpine, and I see lots of disabled options, like apps, google translate, google sync, etc.

Do you think Panthère should automatically define these options too?

**Comment by dunglas** [comment]
No, it's already possible to use extra args. But to me we should stay as close as possible than the Chrome version that will be executed by end users.

**Comment by Pierstoval** [comment]
Ok! Closing then 😄
